"""`schema.graphql` must match what Strawberry actually builds.

WHAT THIS GUARDS. The schema is code-first: there is no schema file to keep in sync, so the public
contract only becomes visible once the code runs, and a change to a type annotation three layers
down can alter it without anyone seeing a diff. This is the diff. It closes the TODO that sat in
app/graphql/schema.py — "no test asserts on the printed SDL yet" — and it exists now specifically
because the type-safety work in docs/type-safety-plan.md is about to retype the domain vocabulary.
A bare `NewType` on a Strawberry field does not silently become a scalar, it raises and the schema
fails to build; but `strawberry.scalar()` DOES change the SDL, quietly, and that is what this
catches.

WHAT IT DOES NOT GUARD. Conformance to `docs/graphql-schema.md`, which is the design agreed before
any resolver existed and still describes `Metric`, `ScoreEntry`, `Mutation` and others this code has
not built. The live schema is a strict subset of that spec today, so asserting equality would fail
on absence rather than on error. That half of the original TODO is still open.

No database: the schema is built from type definitions at import. Verified against an unreachable
DATABASE_URL, and the SDL is byte-identical across processes and PYTHONHASHSEED values.
"""

from __future__ import annotations

from scripts.dump_schema import SCHEMA_FILE, render


def test_the_committed_sdl_matches_what_the_code_builds() -> None:
    committed = SCHEMA_FILE.read_text(encoding="utf-8")

    assert committed == render(), (
        "schema.graphql is out of date with the code that builds it.\n"
        "If the schema changed ON PURPOSE, regenerate and review the diff:\n"
        "    python scripts/dump_schema.py\n"
        "If it did not, something altered the public GraphQL contract as a side effect — which is "
        "exactly what this test exists to surface."
    )


def test_the_snapshot_says_it_is_generated() -> None:
    """A file nobody knows is generated gets hand-edited, and then silently regenerated over."""
    assert SCHEMA_FILE.read_text(encoding="utf-8").startswith("# GENERATED by scripts/dump_schema.py")
