"""initial schema

Revision ID: 001
Revises:
Create Date: 2026-06-30 12:28:37.098709

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concepts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "modules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "module_type",
            sa.Enum("DESIGN", "SCORE", "DESIGN_AND_SCORE", name="moduletype"),
            nullable=False,
        ),
        sa.Column(
            "functions",
            sa.ARRAY(
                sa.Enum(
                    "DE_NOVO_DESIGN",
                    "DIRECTED_EVOLUTION",
                    "FOLDING_LIKELIHOOD",
                    "BINDING_PREDICTION",
                    "DEVELOPABILITY",
                    "AGGREGATION",
                    "STABILITY",
                    "IMMUNOGENICITY",
                    "HYDROPHOBICITY",
                    "EXPRESSION",
                    "EVOLUTIONARY_LIKELIHOOD",
                    "POLYREACTIVITY",
                    name="modulefunction",
                )
            ),
            nullable=False,
        ),
        sa.Column("repo_url", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("recipe_type", sa.String(length=64), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("version", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "targets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("pdb_id", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "experiments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("recipe_id", sa.UUID(), nullable=True),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column("source_filename", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.UUID(), nullable=False),
        sa.Column("column_key", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "value_type",
            sa.Enum("FLOAT", "INT", "BOOL", "CATEGORICAL", name="metricvaluetype"),
            nullable=False,
        ),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column(
            "direction",
            sa.Enum("HIGHER_IS_BETTER", "LOWER_IS_BETTER", "NEUTRAL", name="direction"),
            nullable=False,
        ),
        sa.Column("property_categories", sa.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "variant_kind",
            sa.Enum("PARAMETER", "MODE", "SOURCE_MODEL", "COMPONENT", name="variantkind"),
            nullable=True,
        ),
        sa.Column("variant", sa.String(length=128), nullable=True),
        sa.Column("concept_id", sa.UUID(), nullable=True),
        sa.Column("transform", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["module_id"], ["modules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "module_id",
            "column_key",
            "variant_kind",
            "variant",
            name="uq_metric_identity",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "recipe_modules",
        sa.Column("recipe_id", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["module_id"], ["modules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("recipe_id", "module_id"),
    )
    op.create_table(
        "candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("sequence_id", sa.String(length=255), nullable=False),
        sa.Column("fasta_sequence", sa.Text(), nullable=False),
        sa.Column(
            "scores",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column("annotation", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("experiment_id", "sequence_id", name="uq_candidate_seq"),
    )
    op.create_index("ix_candidates_scores_gin", "candidates", ["scores"], unique=False, postgresql_using="gin")
    op.create_table(
        "artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("uri", sa.String(length=1000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("artifacts")
    op.drop_index("ix_candidates_scores_gin", table_name="candidates", postgresql_using="gin")
    op.drop_table("candidates")
    op.drop_table("recipe_modules")
    op.drop_table("metrics")
    op.drop_table("experiments")
    op.drop_table("targets")
    op.drop_table("recipes")
    op.drop_table("projects")
    op.drop_table("modules")
    op.drop_table("concepts")
    # Postgres ENUM *types* are NOT dropped by drop_table — autogenerate omits this. Drop them
    # explicitly so a downgrade fully reverses the upgrade; otherwise the next upgrade fails with
    # "type ... already exists".  Raw SQL equivalent:  DROP TYPE IF EXISTS moduletype;
    for enum_name in (
        "variantkind",
        "direction",
        "metricvaluetype",
        "modulefunction",
        "moduletype",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
