"""add metric provenance

Revision ID: 002
Revises: 001
Create Date: 2026-07-01 06:17:57.368095

"""

from collections.abc import Sequence
from typing import Final

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: str | Sequence[str] | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PROVENANCE_COLUMN_NAME: Final[str] = "provenance"
METRICS_TABLE_NAME: Final[str] = "metrics"
PROVENANCE_ENUM_NAME: Final[str] = "provenance"
PROVENANCE_ENUM_VALUES: Final[Sequence[str]] = ("INFERRED", "AWS_CONFIRMED")
# First entry is the default — single source of truth, so this can't drift out of sync with the
# enum labels above again the way the old hardcoded "'inferred'" (wrong case) did.
PROVENANCE_COLUMN_DEFAULT: Final[str] = f"'{PROVENANCE_ENUM_VALUES[0]}'"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        METRICS_TABLE_NAME,
        sa.Column(
            PROVENANCE_COLUMN_NAME,
            sa.Enum(*PROVENANCE_ENUM_VALUES, name=PROVENANCE_ENUM_NAME),
            server_default=sa.text(PROVENANCE_COLUMN_DEFAULT),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(METRICS_TABLE_NAME, PROVENANCE_COLUMN_NAME)
    sa.Enum(name=PROVENANCE_ENUM_NAME).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
