"""Require variant_kind and variant to be both set or both null

Revision ID: 008
Revises: 007
Create Date: 2026-08-23 12:07:05.127079

"""

from collections.abc import Sequence
from typing import Final

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "008"
down_revision: str | Sequence[str] | None = "007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

metric_constraint_name: Final[str] = "ck_metric_variant_pair"
metric_table_name: Final[str] = "metrics"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(metric_constraint_name, metric_table_name, "(variant_kind IS NULL) = (variant IS NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(metric_constraint_name, metric_table_name, type_="check")
    # ### end Alembic commands ###
