#!/usr/bin/env python3
"""Write the GraphQL SDL to schema.graphql. Run this when the schema changes on purpose.

    python scripts/dump_schema.py

The file it writes is a SNAPSHOT, not a specification. `docs/graphql-schema.md` holds the design
that was agreed before any resolver existed and still describes types this code has not built yet;
this is what the code actually serves today. `tests/test_schema_snapshot.py` fails when the two
drift, so regenerating is a deliberate act with a reviewable diff rather than something that
happens quietly.

Needs no database: the schema is built from type definitions at import.
"""

from __future__ import annotations

from pathlib import Path
from typing import Final

from app.graphql.schema import schema

_REPO_ROOT: Final[Path] = Path(__file__).resolve().parents[1]
SCHEMA_FILE: Final[Path] = _REPO_ROOT / "schema.graphql"

_BANNER: Final[str] = (
    "# GENERATED by scripts/dump_schema.py — do not hand-edit.\n"
    "# This is what the code serves. docs/graphql-schema.md is what was designed;\n"
    "# it still describes types that are not built yet, so the two are not the same file.\n"
    "# tests/test_schema_snapshot.py fails if this drifts from strawberry's output.\n\n"
)


def render() -> str:
    """The exact bytes the snapshot file should contain."""
    return _BANNER + schema.as_str() + "\n"


def main() -> None:
    SCHEMA_FILE.write_text(render(), encoding="utf-8")
    print(f"wrote {SCHEMA_FILE.relative_to(_REPO_ROOT)} ({len(render())} bytes)")


if __name__ == "__main__":
    main()
